---
version: '3'

services:
  traefik:
    image: traefik:v2.2
    command: --api.insecure=false --providers.docker
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8010:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - traefik-data:/data
    environment:
      - "CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}"
    restart: always

volumes:
  traefik-data:

networks:
  default:
    external:
      name: front
