providers:
  docker: {}

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

certificatesResolvers:
  dnsresolver:
    acme:
      email: me@example.com
      storage: /data/acme.json
      dnsChallenge:
        provider: cloudflare
